<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PV Ground mounted</name>
   <tag></tag>
   <elementGuidId>93ced787-7563-4739-938b-315dfa99d3b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-DeviceTechnology-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-DeviceTechnology-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fbb9facb-baf0-491c-bab2-dff402859a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-select-responsive input-field__option field-select-responsive input-field__option--is-focused css-pal6qc-option</value>
      <webElementGuid>c35de8bf-ba7e-4896-8e25-ce0eda13c614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25d26222-be35-484b-8029-d565ea20b389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-DeviceTechnology-option-0</value>
      <webElementGuid>77473634-7651-4e44-8c2e-1fe4737c821d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2617d101-fa44-4256-9eff-d43c613a3313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PV Ground mounted</value>
      <webElementGuid>ef8808dd-39be-4065-9e9d-d9085eda7cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-DeviceTechnology-option-0&quot;)</value>
      <webElementGuid>f6d3da8c-cbae-4489-98ad-2378002e27de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-DeviceTechnology-option-0']</value>
      <webElementGuid>2b2fe5b5-9f08-45fe-8cfc-6dd316d6a029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-DeviceTechnology-listbox']/div/div</value>
      <webElementGuid>8e777804-f8d7-4f8f-a0db-8133aa2fca31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::div[6]</value>
      <webElementGuid>71cbfa65-b68f-48bb-8453-4d7601ded78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[10]</value>
      <webElementGuid>8c3ff299-ddb9-40a2-8994-b51dc2998586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PV Floating'])[1]/preceding::div[1]</value>
      <webElementGuid>dfcef6c4-2e8c-4101-93d8-facfc21d494a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PV Aggregated'])[1]/preceding::div[2]</value>
      <webElementGuid>ec65cf93-b032-4c7a-8205-2f77d68eda7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PV Ground mounted']/parent::*</value>
      <webElementGuid>58620772-ffd7-4a10-b533-339bc303bca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div</value>
      <webElementGuid>6da0751c-9f61-4ecd-b9e8-1d12b59f9594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-DeviceTechnology-option-0' and (text() = 'PV Ground mounted' or . = 'PV Ground mounted')]</value>
      <webElementGuid>31eaf9dd-a024-4383-b120-bca91db407f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
