<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Solar</name>
   <tag></tag>
   <elementGuidId>f9e3420e-8664-4d19-aad8-d53256ad177f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-DeviceFuel-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-DeviceFuel-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e4a4b0f-07de-4a01-8484-4b97ff697bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-select-responsive input-field__option field-select-responsive input-field__option--is-focused css-pal6qc-option</value>
      <webElementGuid>1c252d40-b0f1-40b9-816e-1e260e93f909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52642534-5d74-4120-92b4-0f96ee08be7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-DeviceFuel-option-1</value>
      <webElementGuid>c6971cea-4072-4f08-877b-d6e7531e5bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c07ac51c-e140-46aa-b25e-c842256e7679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solar</value>
      <webElementGuid>b9f60266-a086-4b66-a98e-a0fdacb52ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-DeviceFuel-option-1&quot;)</value>
      <webElementGuid>dbcfeab5-52e9-4b94-b695-f680559b3928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-DeviceFuel-option-1']</value>
      <webElementGuid>3e5133ab-c117-4375-95a9-a07874a92ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-DeviceFuel-listbox']/div/div[2]</value>
      <webElementGuid>24e883f5-6333-4541-b16d-49368304b8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wind'])[1]/following::div[1]</value>
      <webElementGuid>c7b617b5-f9c9-4196-8b12-daa84291487d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Device Fuel'])[1]/following::div[7]</value>
      <webElementGuid>5e8dea1d-9ca0-4ea3-aa58-44a99a7a8813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hydro-electric'])[1]/preceding::div[1]</value>
      <webElementGuid>c467f641-7992-48ef-a44c-13ff8cea97e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marine Tidal'])[1]/preceding::div[2]</value>
      <webElementGuid>95bad96e-9dc2-49a1-a55d-bef9d5181467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solar']/parent::*</value>
      <webElementGuid>0e9ffc60-c997-4502-90b8-9952ebd7ec62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>f8b9bad2-f33b-4bd2-97da-f62ffde0ab42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-DeviceFuel-option-1' and (text() = 'Solar' or . = 'Solar')]</value>
      <webElementGuid>1bfa4ca3-0a57-44c7-9213-3632fb225cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
