<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PostCode</name>
   <tag></tag>
   <elementGuidId>d6588b76-1dc7-4dc6-9d80-241bdc6cdd24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='PostCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;PostCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8245b6a-9b03-4459-bb79-9c0beab1f00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostCode</value>
      <webElementGuid>0e25c5cd-3bcb-4f78-8e47-cd8631135048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>380a73d9-510e-49d7-aa60-c4af1e070840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>698ca7a0-8499-4466-ab67-0f447644877e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;flex flex-col justify-center items-center&quot;]/div[@class=&quot;mt-8 w-5/12&quot;]/form[1]/div[1]/div[@class=&quot;border-shadow-container bg-white&quot;]/div[@class=&quot;p-4&quot;]/fieldset[@class=&quot;w-full flex gap-4 justify-between&quot;]/div[@class=&quot;w-1/2&quot;]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>21fd1308-7fd0-4874-8313-91ba82f6e21e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='PostCode']</value>
      <webElementGuid>8311eed0-c153-48f3-b150-a9b1156ea03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/form/div/div/div/fieldset[3]/div[2]/div/div/input</value>
      <webElementGuid>9841c01d-6bcc-4fcb-8262-4869804ea8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8ab3b830-0fcc-40b9-9a47-e0fb8fc68421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'PostCode' and @type = 'Text']</value>
      <webElementGuid>f40bc864-f05f-4f16-86b0-d8d212fe6c95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
