<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_Notes</name>
   <tag></tag>
   <elementGuidId>2f2cf6db-c674-41e9-a7a9-9bf3ca0830b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='Notes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Notes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aa6d60b5-161e-43d8-b13b-ace4eec38d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>2b1b7a0d-343c-4ef0-9f8c-73baa806cc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- gUeJc</value>
      <webElementGuid>1b83dd10-0d63-4a83-aeb4-e0865ffc1492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>26a7f5f0-16de-461b-a8e7-12dd85e08a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;m-auto w-1/2 mt-4 relative&quot;]/div[@class=&quot;mt-8&quot;]/form[1]/section[@class=&quot;border-shadow-container bg-white mt-4&quot;]/div[@class=&quot;px-4 pb-4&quot;]/div[@class=&quot;jCXzE&quot;]/textarea[@class=&quot;Ll29B ouzj- gUeJc&quot;]</value>
      <webElementGuid>72e12811-675c-42ff-a714-a83c0b9f0d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='Notes']</value>
      <webElementGuid>21fb4466-29ec-467d-86b0-72b96e22d803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/form/section/div[2]/div/textarea</value>
      <webElementGuid>eb3a59cc-02dd-478d-93cf-acb51b672f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5e57fc69-e649-4361-829f-3208443a474a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Notes']</value>
      <webElementGuid>b512eafb-db6f-4e6e-b6f3-ed2a06fcbefa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
