<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TIGR</name>
   <tag></tag>
   <elementGuidId>2443bca6-b442-4ac7-99d4-4f4b808d44ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-Registry-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-Registry-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f5f6302-b547-4422-9680-bde59cebd8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-select-responsive input-field__option field-select-responsive input-field__option--is-focused css-pal6qc-option</value>
      <webElementGuid>cc8dc083-d961-4b0a-afb2-1d2cba0495bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b41f3021-4b56-46e1-bf79-cd17441ad1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-Registry-option-1</value>
      <webElementGuid>c5c4302d-7955-4586-9771-620af223dcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c780ece4-1de4-4f2b-974e-857143facd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIGR</value>
      <webElementGuid>31730498-2e37-409f-a546-05f18cfab7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-Registry-option-1&quot;)</value>
      <webElementGuid>8ceeafae-c473-46ce-8f8b-231aa71db606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-Registry-option-1']</value>
      <webElementGuid>1e8bdbdf-ff8b-4243-a3f1-dfb301c40d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-Registry-listbox']/div/div[2]</value>
      <webElementGuid>55c454fc-05a9-4584-b95d-9db2c4a290b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I-REC'])[1]/following::div[1]</value>
      <webElementGuid>b8c7dd04-d829-40db-ad29-37db3daa0295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Registry'])[1]/following::div[7]</value>
      <webElementGuid>3a23df3a-0913-486d-a84b-fedb727e5740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-select-Registry-option-1', '&quot;', ')')])[1]/preceding::div[5]</value>
      <webElementGuid>efa1d8a0-e32f-474b-866c-b22f7161e298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/preceding::div[19]</value>
      <webElementGuid>ef7a2e09-90ce-4c93-aa90-864d48562a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TIGR']/parent::*</value>
      <webElementGuid>863fef57-b20e-4a5b-a1e3-fa849b2e7453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>51d56ee6-0cf1-4f4f-ad98-40310fcdb16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-Registry-option-1' and (text() = 'TIGR' or . = 'TIGR')]</value>
      <webElementGuid>e0438782-1c79-4d42-8ec1-ff37b80a6e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
