<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Information Correct_DocumentsAreValid</name>
   <tag></tag>
   <elementGuidId>3fed57f8-d557-4791-8392-7e66f3e99122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DocumentsAreValid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DocumentsAreValid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35abac84-98a6-40e9-b3cc-805ad4975d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DocumentsAreValid</value>
      <webElementGuid>fb80c46d-ef33-4206-8463-255523bac9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>63fff74b-a42f-476c-99c0-646c5aa01669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentsAreValid</value>
      <webElementGuid>657a0def-03cb-4333-8d5a-3370a3c6b8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6449b95a-76b8-40ad-a6ed-57ed0f26a921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B</value>
      <webElementGuid>7362faee-ad82-4bb1-ba38-dc8c8a586638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentsAreValid&quot;)</value>
      <webElementGuid>cb90dba7-0023-4eb8-853b-26e9b26d635e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DocumentsAreValid']</value>
      <webElementGuid>f21636e7-8885-4ea5-bb1c-c75fb27833f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section/div[2]/form/div/div[2]/div/label/input</value>
      <webElementGuid>b4c1dec3-2799-4e7a-b2c4-59dce959faa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>ac989a26-f928-43bb-93cf-89052f1d9901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DocumentsAreValid' and @placeholder = 'Required' and @id = 'DocumentsAreValid' and @type = 'checkbox']</value>
      <webElementGuid>bbd74626-82fb-40df-8c4d-8bd8be4e2901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
