<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Submit</name>
   <tag></tag>
   <elementGuidId>8691c5ed-154c-406c-81ae-0d7670235dd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section[3]/div[2]/section/div/div/div/button/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.rehash-ui-button__content.color-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>be55fa4f-17db-4ffd-8b16-f9233247b8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rehash-ui-button__content color-white</value>
      <webElementGuid>8067ec0b-c449-4678-8df2-b481465071db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>758788ee-42e9-41df-979f-c0e83d5ce9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/div[@class=&quot;mt-4 mx-6 mb-4&quot;]/div[@class=&quot;grid grid-cols-12 md:gap-5 lg:gap-8 mb-4&quot;]/div[@class=&quot;col-span-3 flex flex-col gap-4&quot;]/section[@class=&quot;border-shadow-container bg-white flex flex-col p-4 gap-2 shadow-container&quot;]/div[@class=&quot;border-t-2 pt-2&quot;]/section[@class=&quot;f-RcU relative&quot;]/div[@class=&quot;kshVJ&quot;]/div[1]/div[@class=&quot;UWI-X&quot;]/button[@class=&quot;bg-green rehash-ui-button rehash-ui-button__default rehash-ui-button__disabled&quot;]/p[@class=&quot;rehash-ui-button__content color-white&quot;]</value>
      <webElementGuid>010636c2-fe42-4035-be16-cdd7f841a861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section[3]/div[2]/section/div/div/div/button/p</value>
      <webElementGuid>e8d15981-a5a7-401e-8710-b6b1b38c9126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[1]</value>
      <webElementGuid>e646960b-c2dd-4c91-8e47-b24f2ed4ea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::p[2]</value>
      <webElementGuid>8c2189fe-6d65-4157-899d-2b9f53012b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/preceding::p[6]</value>
      <webElementGuid>2669c076-96f2-4532-bae9-543281268ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[2]/preceding::p[6]</value>
      <webElementGuid>d9f8bbaa-4276-444e-ab97-9e6c2dcf0617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>c8eb6617-999b-4b09-a288-2c884430030f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/button/p</value>
      <webElementGuid>e8ecd444-f2df-4b5c-bb71-ea8fc2a40545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>b430b98f-cb1f-4c23-834b-90d6e957fe1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
