<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View (1)</name>
   <tag></tag>
   <elementGuidId>fe290c7f-171b-4884-b781-0ab5bb392b3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edf0fde8-fc04-4a1f-a93a-36c89b92b4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-primary font-bold hover:underline focus:underline text-xs</value>
      <webElementGuid>f9724d6a-1cd4-45a5-9b03-730fd936718a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/finances/transaction/accounts-receivable/INV-REAR-2023-05-10-00017</value>
      <webElementGuid>330ae221-2b80-46be-a72a-a7aaddcb19fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>ee7106dc-c39e-406c-8a27-5ec6d56db502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/section[@class=&quot;py-4 mx-6 h-full&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;ttzJ8&quot;]/div[@class=&quot;Jybgt w-full h-full overflow-x-auto&quot;]/table[@class=&quot;oL4Dz&quot;]/tbody[1]/tr[@class=&quot;r7tV0&quot;]/td[@class=&quot;I4pE5 text-center&quot;]/a[@class=&quot;color-primary font-bold hover:underline focus:underline text-xs&quot;]</value>
      <webElementGuid>bb421a1b-1e3d-41b6-a1d3-8e7135184ecf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[13]/a</value>
      <webElementGuid>e7e7e5bd-89a6-4895-a7a1-ed78811fbee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>cd9f4ded-be91-44cf-9945-f205221abfa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.09'])[2]/following::a[1]</value>
      <webElementGuid>057badab-3d21-4e20-b340-49475b06aa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.09'])[1]/following::a[1]</value>
      <webElementGuid>5a011b91-e96c-402f-bd0e-418d4b204b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/preceding::a[1]</value>
      <webElementGuid>deb47712-82c4-4c18-91b9-02b273da47d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>e7268319-9ba9-4b12-8ce2-cfd237a03503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/finances/transaction/accounts-receivable/INV-REAR-2023-05-10-00017')]</value>
      <webElementGuid>acf41d72-246d-461e-a03a-e54a328929ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/a</value>
      <webElementGuid>386abfc4-5d86-4837-a9d0-b56c044a9a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/finances/transaction/accounts-receivable/INV-REAR-2023-05-10-00017' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>88c4168e-fd6a-4478-9d00-2515cf1962b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
