<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remark_RemarkContent</name>
   <tag></tag>
   <elementGuidId>949a3f6c-19b3-40a6-84c1-d6c178951f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='RemarkContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;RemarkContent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bfd5af93-15bd-41bb-b2f3-bf672a89a705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RemarkContent</value>
      <webElementGuid>806ccd93-dc18-477a-9db8-04ef2da7540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- -px3b</value>
      <webElementGuid>402415ff-f09d-4188-9a94-a03fab3e7420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>670ee502-dcf1-4fc7-b936-b2349d8ebd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>779c7b5d-510e-4885-a36d-283378e1ef65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/reach-portal[4]/div[2]/div[1]/div[1]/div[@class=&quot;Mow1G&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;xOMCj&quot;]/div[@class=&quot;jCXzE&quot;]/textarea[@class=&quot;Ll29B ouzj- -px3b&quot;]</value>
      <webElementGuid>cbcb301d-6a9e-4c9f-b19f-354586440c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='RemarkContent']</value>
      <webElementGuid>1851e880-43a3-4c00-86fe-6f02787f8d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2a012114-f9e5-479d-a5e5-2553fc6053b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'RemarkContent' and @placeholder = 'Input']</value>
      <webElementGuid>b1e36d04-3128-469a-975d-b7ca4a4ea512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
