<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PostCode</name>
   <tag></tag>
   <elementGuidId>407ca626-d458-4643-a894-991c6d79307b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;PostCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='PostCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c04c30f5-a284-4ec4-a92b-cb44a633501f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostCode</value>
      <webElementGuid>6b50b3ca-0db3-4128-8926-0a645586ab66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>86512ae4-ecd4-4967-9996-d4158886ea3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Post Code</value>
      <webElementGuid>0bafdee6-79d5-4b00-b619-0437715e7615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>0209ec2d-d03c-458f-9639-c621e8b88e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;nLQpU&quot;]/div[@class=&quot;_05-FX&quot;]/form[@class=&quot;bg-white border-shadow-container&quot;]/div[4]/div[@class=&quot;flex flex-col px-4 pb-4&quot;]/fieldset[@class=&quot;pl-0&quot;]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>07981bed-4b2d-4d42-bb53-679cd4056081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='PostCode']</value>
      <webElementGuid>6697cbdb-f7c3-4656-98d8-d30829e3e491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div/form/div[4]/div[2]/fieldset[4]/div/div/input</value>
      <webElementGuid>4d68d77c-a934-43da-b434-0f0be44acc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/fieldset[4]/div/div/input</value>
      <webElementGuid>279b91ab-7b93-4729-86cf-6878aae06776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'PostCode' and @placeholder = 'Post Code' and @type = 'Text']</value>
      <webElementGuid>a9eae512-8c95-49f7-98b1-7c5dc5c2c642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
