<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Company, , s English Name)_Eng_d5971c</name>
   <tag></tag>
   <elementGuidId>e0ebae6b-a190-4197-b45c-fa752c91cc12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;EnglishCompanyName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EnglishCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6e796a8-496b-4750-8612-90dac4ee3a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EnglishCompanyName</value>
      <webElementGuid>b4ec6e77-cfac-4dac-9dc5-db3f791ca2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>1f962f5b-c4a7-4c55-9dd3-1b6dd63a0d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company's English Name</value>
      <webElementGuid>9a2deaa6-2adc-4aeb-9d32-7d342ba0c634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>ec0fab0d-8839-47c9-abd3-2bbbb25c4298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;nLQpU&quot;]/div[@class=&quot;_05-FX&quot;]/form[@class=&quot;bg-white border-shadow-container&quot;]/section[@class=&quot;eVbPK p-4&quot;]/div[@class=&quot;Djrcb&quot;]/div[@class=&quot;BMtxm flex flex-col gap-4&quot;]/div[@class=&quot;x3VmX&quot;]/div[1]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>454c3906-0241-434d-92bd-55adb58fa9f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='EnglishCompanyName']</value>
      <webElementGuid>01005539-b14f-4470-83fd-88cfc1967b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div/form/section/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>cb3516e3-a7a4-49f7-aa36-687865af3b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>e9cf0ca5-04ce-4f26-9368-baf968a8b4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EnglishCompanyName' and @placeholder = concat(&quot;Company&quot; , &quot;'&quot; , &quot;s English Name&quot;) and @type = 'Text']</value>
      <webElementGuid>2e037f93-82e6-4afe-a9be-ded93d841371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
