<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__SwiftCode</name>
   <tag></tag>
   <elementGuidId>c3820adb-10a3-4940-8afb-cf39a237be7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SwiftCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SwiftCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b435ad66-fa2b-4ffd-bcd8-8cedff4f14a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SwiftCode</value>
      <webElementGuid>051fd209-4f97-409c-80be-80754f70cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>018e0fa1-4ded-45f1-b0df-ddb024c7aee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AAAAAA-BB(12) or AAAAAA-BBBBB(12345)</value>
      <webElementGuid>4bada956-463e-42d9-a85c-435dcbe1e1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>7240b14d-99d1-42c4-ae74-141d9e1cbdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;nLQpU&quot;]/div[@class=&quot;_05-FX&quot;]/form[@class=&quot;bg-white border-shadow-container&quot;]/div[2]/div[@class=&quot;flex flex-col px-4 pb-4&quot;]/fieldset[@class=&quot;pl-0&quot;]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>0613c3a4-f95f-4403-a4e7-1a730890f8ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SwiftCode']</value>
      <webElementGuid>429a5c86-5b8a-4d4b-97cb-7ca8929d49d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div/form/div[2]/div[2]/fieldset[3]/div/div/input</value>
      <webElementGuid>2209a170-a8d5-45e5-86f6-816d056803b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/input</value>
      <webElementGuid>691d3c1d-eba2-4b31-add8-666cf51431a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SwiftCode' and @placeholder = 'AAAAAA-BB(12) or AAAAAA-BBBBB(12345)' and @type = 'Text']</value>
      <webElementGuid>94d73407-8a97-47d1-9fb0-31b8e0123e24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
