<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__City (ACH)</name>
   <tag></tag>
   <elementGuidId>c34905b1-1226-4af2-ae7f-103f1f301042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;City&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>739773dc-92de-4ec0-a5bb-b54bc6d238cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>fc2a667e-4de8-4191-a15e-d72373db7ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>a995db93-9cdb-4541-b64d-a4a62aa8d2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>24996c9e-36be-40de-92d7-4ef28c534ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>76a9d73b-882d-4c6d-a173-cb6501374a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;nLQpU&quot;]/div[@class=&quot;_05-FX&quot;]/form[@class=&quot;bg-white border-shadow-container&quot;]/div[4]/div[@class=&quot;flex flex-col px-4 pb-4&quot;]/fieldset[@class=&quot;pl-0&quot;]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>f3b13e1b-223f-4367-8a3d-384bc0b3bbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='City']</value>
      <webElementGuid>349e9aef-bc55-4611-b9a9-aba8c665ea30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div/form/div[4]/div[2]/fieldset[2]/div/div/input</value>
      <webElementGuid>d18aa54b-9786-46bb-ae9d-dbcf8de3a138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/fieldset[2]/div/div/input</value>
      <webElementGuid>cb8829e1-eb28-4b2d-9012-3318a91e84b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'City' and @placeholder = 'City' and @type = 'Text']</value>
      <webElementGuid>f0db5f8b-f642-4f9e-a86d-c2cddc6ac888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
