<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Company, , s English Name)_EnglishCompanyName</name>
   <tag></tag>
   <elementGuidId>3dcff8b0-2082-4e1f-9603-336045ddff6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;EnglishCompanyName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EnglishCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81293a6e-611e-420a-a2c3-7b8f3407f58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EnglishCompanyName</value>
      <webElementGuid>f56ec315-78b5-48fe-8219-b7190fdcc1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>0b5af524-8dfa-4bcf-bf64-29eaa8adda74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company's English Name</value>
      <webElementGuid>ba5c2eab-436e-4df3-9844-47b382961f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>609d31d9-df51-4e66-9b8e-6a589d802afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;nLQpU&quot;]/div[@class=&quot;_05-FX&quot;]/form[@class=&quot;bg-white border-shadow-container&quot;]/section[@class=&quot;eVbPK p-4&quot;]/div[@class=&quot;Djrcb&quot;]/div[@class=&quot;BMtxm flex flex-col gap-4&quot;]/div[@class=&quot;x3VmX&quot;]/div[1]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>0099c461-1652-4dad-bc7b-0dad4c517916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='EnglishCompanyName']</value>
      <webElementGuid>953afcfd-97be-461a-ab63-7728bacb6778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div/form/section/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>fd5c8598-067d-4732-95e3-f774c0078987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>a8fb5b04-cb5b-41e6-9ad1-715340481512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EnglishCompanyName' and @placeholder = concat(&quot;Company&quot; , &quot;'&quot; , &quot;s English Name&quot;) and @type = 'Text']</value>
      <webElementGuid>e1bbd049-2e68-46fe-b14b-cadc0cf2991a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
