<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REC Retirement</name>
   <tag></tag>
   <elementGuidId>5c32c915-bd57-4917-994f-af5586be9d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/ul/li[3]/div/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a._5YcdN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17ebf835-b53c-4def-bcb0-170c8f48c25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_5YcdN</value>
      <webElementGuid>709f9f5d-03f6-4e36-be3a-3f0cc5604781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/503525b1-1eaa-49f5-f735-08daa10bfc10/clients/rec-retirements</value>
      <webElementGuid>b80b8dc8-a8f3-47f4-b86d-865468e070c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REC Retirement</value>
      <webElementGuid>1b91433e-8cf7-4a31-84d8-467cdf81cbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;as0Kr&quot;]/div[@class=&quot;_2o6Ag&quot;]/div[@class=&quot;_1WbnP&quot;]/ul[@class=&quot;w-full mt-4&quot;]/li[3]/div[@class=&quot;w-full&quot;]/div[@class=&quot;p-4 border-t-2&quot;]/ul[@class=&quot;ErF7Y _5Xp9e&quot;]/li[4]/a[@class=&quot;_5YcdN&quot;]</value>
      <webElementGuid>7ad79177-f533-4dba-9485-a01565d6bff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/ul/li[3]/div/div/ul/li[4]/a</value>
      <webElementGuid>e8bed9d2-4b3f-44d4-b7df-45df2f80d50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REC Retirement')]</value>
      <webElementGuid>77156a3d-3e86-4032-a00d-ce3e1d0f2a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REC Imports'])[1]/following::a[1]</value>
      <webElementGuid>fd737397-43c9-4064-9bcf-4ddd49cb59e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REC Registration'])[1]/following::a[2]</value>
      <webElementGuid>7ac66a94-175d-4cfe-ad6a-ae31e7a1f935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/preceding::a[1]</value>
      <webElementGuid>c5fc0961-c3ef-4fda-996a-d7f6c5fd28c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset'])[1]/preceding::a[1]</value>
      <webElementGuid>7791c316-8f0f-4c88-b2bf-87b145f938d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REC Retirement']/parent::*</value>
      <webElementGuid>54a31872-b5e0-41ae-9c53-9b101547256e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/503525b1-1eaa-49f5-f735-08daa10bfc10/clients/rec-retirements')]</value>
      <webElementGuid>35496f5c-3c8a-4709-93da-d5d8c2b6b50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>75bc540e-c490-4f4f-92a7-c4923c7ae813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/503525b1-1eaa-49f5-f735-08daa10bfc10/clients/rec-retirements' and (text() = 'REC Retirement' or . = 'REC Retirement')]</value>
      <webElementGuid>361a5ba0-c9a5-4608-9a83-91fc21be9ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
