<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>52103e23-e4cf-4426-a52a-f82a2eb5cd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44a61b71-d609-4462-a028-644c210cfe8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-primary font-bold hover:underline focus:underline text-xs</value>
      <webElementGuid>13eb3e21-4c58-4dd7-a055-db36399bf23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/finances/transaction/accounts-receivable/INV-REAR-2023-05-10-00018</value>
      <webElementGuid>15b99831-10b7-4bbd-ae79-23ada859df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>6cff88ee-c128-46dd-b47c-22f059d9066c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/section[@class=&quot;py-4 mx-6 h-full&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;ttzJ8&quot;]/div[@class=&quot;Jybgt w-full h-full overflow-x-auto&quot;]/table[@class=&quot;oL4Dz&quot;]/tbody[1]/tr[@class=&quot;r7tV0&quot;]/td[@class=&quot;I4pE5 text-center&quot;]/a[@class=&quot;color-primary font-bold hover:underline focus:underline text-xs&quot;]</value>
      <webElementGuid>680627c1-542b-4c56-b90a-13ba4fc97e87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[13]/a</value>
      <webElementGuid>b3d678d0-2fb1-4c78-81bc-687fde8828e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>5475da1d-62e1-46d2-a454-d5128e877c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.09'])[2]/following::a[1]</value>
      <webElementGuid>96fd0a69-6f3b-4d88-8801-9d14d5a658fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.09'])[1]/following::a[1]</value>
      <webElementGuid>a5a0d6b5-25da-42ef-a537-3f1d6b6d99e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/preceding::a[1]</value>
      <webElementGuid>680c6468-be7a-4ad1-b9c4-9bdce9cf172f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>5469aa8b-b7ec-4c08-b488-9d2fa5cac8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/finances/transaction/accounts-receivable/INV-REAR-2023-05-10-00018')]</value>
      <webElementGuid>9ab67764-0d14-4efc-9aa2-f48eb064d92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/a</value>
      <webElementGuid>45b30290-dcf3-42ec-a9ad-ac96e6566c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/finances/transaction/accounts-receivable/INV-REAR-2023-05-10-00018' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>e4c9f0ed-e7fb-4bbb-9539-b3bf2fa42d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
