<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>e03ca652-bf9a-4ae2-9c77-70c1e366b2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.rehash-ui-legacy-button.rehash-ui-legacy-button__primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>269f26c4-5ba2-4a31-b8ba-7d20aa9721d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>044cb62e-4847-4be3-8efd-4fa21e1c37fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rehash-ui-legacy-button rehash-ui-legacy-button__primary</value>
      <webElementGuid>d4201887-912b-4daa-a50d-755f0c54d769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>5c2ca9e4-1550-460c-90a1-458d4c630abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/reach-portal[5]/div[2]/div[1]/div[1]/div[@class=&quot;GXjm0&quot;]/div[2]/div[@class=&quot;vej--&quot;]/div[3]/div[@class=&quot;l-R-g&quot;]/button[@class=&quot;rehash-ui-legacy-button rehash-ui-legacy-button__primary&quot;]</value>
      <webElementGuid>6a644dfd-1a68-4c34-8260-746c49a3dd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>75dd87ce-ac0d-4cba-a415-78a3332b117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redemption Information'])[1]/following::button[2]</value>
      <webElementGuid>bf9355f8-7072-4928-ae48-b20c3788e15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning!'])[1]/following::button[2]</value>
      <webElementGuid>149485e9-14aa-4eb9-900a-ab6e1f20796c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>b6551e59-ecff-4f97-a962-7e8f55147640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>fc481ecd-0600-4ca9-9a60-99e8eb05337f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
