<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ShowingtoofItem(s)_flex justify-center items-center bg-black bg-opacity-30 h-screen w-screen fixed top-0 left-0 z-1002</name>
   <tag></tag>
   <elementGuidId>0a939897-772f-4f9f-89f8-b24d48ec336d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-center.items-center.bg-black.bg-opacity-30.h-screen.w-screen.fixed.top-0.left-0.z-1002</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6fd39993-6104-4295-b90b-f2cc393f0ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-center items-center bg-black bg-opacity-30 h-screen w-screen fixed top-0 left-0 z-1002</value>
      <webElementGuid>cc0bb23c-9068-46cd-ad45-48afd7bfb9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;as0Kr&quot;]/section[@class=&quot;B-aoL js-wrapper-scrollEffect padding-footer&quot;]/div[@class=&quot;flex justify-center items-center bg-black bg-opacity-30 h-screen w-screen fixed top-0 left-0 z-1002&quot;]</value>
      <webElementGuid>c7a6723a-5a2a-413f-b834-25d2796ef6e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div</value>
      <webElementGuid>2c15fa3c-fd36-4bd7-a982-80f552f41b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[10]/following::div[19]</value>
      <webElementGuid>8cdbe111-83a8-4d25-a0e6-21741701bdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[4]</value>
      <webElementGuid>80b8620a-1602-43df-8ea5-db6918ba9b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[4]</value>
      <webElementGuid>4706a956-0477-4163-9c91-e0e4b03f1c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>5b548491-c093-4380-b031-173df387bc86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
