<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remark_RemarkContent_1</name>
   <tag></tag>
   <elementGuidId>910272b5-74f4-408c-8f4f-f856149aca0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='RemarkContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;RemarkContent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4b16166e-5ddf-4524-a463-1ad6e563f999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RemarkContent</value>
      <webElementGuid>9eea10f5-5838-4570-9a7c-607291386d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- -px3b</value>
      <webElementGuid>2a8413c1-9ca3-4126-9a8b-f2c5d7e15689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>4695fc3f-5c6b-4646-8b78-1afd2bf3256c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3383c2e9-dd1b-41a2-a627-a5b779c67579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/reach-portal[4]/div[2]/div[1]/div[1]/div[@class=&quot;Mow1G&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;xOMCj&quot;]/div[@class=&quot;jCXzE&quot;]/textarea[@class=&quot;Ll29B ouzj- -px3b&quot;]</value>
      <webElementGuid>4c432c6c-72a5-499e-914c-aff279d6e721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='RemarkContent']</value>
      <webElementGuid>d9e54c82-c791-4989-9433-fc69d63a1d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cffc07b7-fee0-4881-b6ef-cb82570c57ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'RemarkContent' and @placeholder = 'Input']</value>
      <webElementGuid>f8bd0e1a-53dc-4480-9c92-a0cca3cc44d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
