<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remark_RemarkContent</name>
   <tag></tag>
   <elementGuidId>a09f070c-7888-4e06-9003-88b24522b1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='RemarkContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;RemarkContent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>22f9bcc2-4f81-462d-93e0-565642ef9479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RemarkContent</value>
      <webElementGuid>4be76273-afc1-4b30-8d62-5d219b2d372a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field mt-2</value>
      <webElementGuid>7742c183-94fc-4718-9950-b9c33e5a08e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>09562fdc-7247-4dff-8ad1-d43494d6f2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/reach-portal[3]/div[2]/div[1]/div[1]/div[@class=&quot;Mow1G NW1R-&quot;]/div[2]/form[1]/div[@class=&quot;_7QyNv&quot;]/div[@class=&quot;jCXzE&quot;]/textarea[@class=&quot;Ll29B ouzj- input-field mt-2&quot;]</value>
      <webElementGuid>61f53dd6-9073-44b8-aa89-f2322be96439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='RemarkContent']</value>
      <webElementGuid>94f67e44-c07d-4123-a6ae-3d9d96dadc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3f909f44-022b-4492-b230-2907f995583f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'RemarkContent']</value>
      <webElementGuid>ddc3fe6a-7c2a-4f27-a17b-a3be4608a5f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
