<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProjectName</name>
   <tag></tag>
   <elementGuidId>a547e08a-6660-4d8b-9958-95877c1d77e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ProjectName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ProjectName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2eccb62c-b37f-42cd-a7b8-e598246198ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProjectName</value>
      <webElementGuid>543205fc-0ea6-4078-8957-5be38937a924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>179fbc68-42a1-4f8c-b62a-d3a590ad8ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>5d4c8240-b3c7-42fa-baa8-edaab6e7342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;xIB0Q&quot;]/div[@class=&quot;mt-8 w-5/12&quot;]/form[1]/div[@class=&quot;border-shadow-container bg-white&quot;]/div[@class=&quot;p-4 flex flex-col&quot;]/fieldset[1]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>65e58cae-58fc-4e81-bb2a-7002f51e2a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ProjectName']</value>
      <webElementGuid>d1aadb0a-2729-4e7c-b783-688a1bd346c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/form/div/div/fieldset/div/div/input</value>
      <webElementGuid>329ae09f-22a7-416a-a600-70bea55d6cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>80e5a930-d3ad-4df4-a84f-b3f288637a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ProjectName' and @type = 'Text']</value>
      <webElementGuid>2359ceaa-6e74-409f-887f-ac51c9dd4cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
