<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CheckCondition</name>
   <tag></tag>
   <elementGuidId>b2ebd89e-1b1f-44b0-8c6b-2e0a352e2a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CheckCondition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CheckCondition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0533b6f-40f8-4c0a-8fff-91573a652975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckCondition</value>
      <webElementGuid>fc548fca-fcd7-45e8-af7f-758df5a6163f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CheckCondition</value>
      <webElementGuid>37ae4051-e5cc-413b-8ff1-4b80ca655c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>785eb1fe-9a8d-49e0-83ce-c4dacffb1ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B</value>
      <webElementGuid>094bf073-f0b3-445c-98a1-e89845d94b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CheckCondition&quot;)</value>
      <webElementGuid>e3e5f99e-7cf5-4b85-950c-0c0d3ae46fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CheckCondition']</value>
      <webElementGuid>6876943f-9654-4630-b524-1b20e6890380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/form/div/fieldset[7]/div/label/input</value>
      <webElementGuid>001ce535-e91f-4d90-b900-7ed43988a29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>a7f1d4e7-874f-4a6e-bbe5-356892a3f989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CheckCondition' and @id = 'CheckCondition' and @type = 'checkbox']</value>
      <webElementGuid>811f5f6b-442f-490e-8191-2e04fb7403cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
