<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__StartDate</name>
   <tag></tag>
   <elementGuidId>4a52a943-f3cc-4aa6-9018-97bbfed6fa0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='StartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30e7d31e-6394-4e66-a269-1a34540f6b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e3c7b64-269b-4b3b-afb2-ea87d7a73b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StartDate</value>
      <webElementGuid>0ed3b880-9435-4994-a22f-9b203bf67ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartDate</value>
      <webElementGuid>a4b39b93-03ea-4c46-b013-a6726bc0ebf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>e96df2f9-4e5d-49c5-a6e7-4b49614a9ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>59bf50dc-392f-44ff-9754-26dfb3a7a995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>310d5c64-748d-4fa6-91b8-3cdb7ce9493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StartDate&quot;)</value>
      <webElementGuid>f51843cd-8413-4fe4-b39e-42e60935cac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='StartDate']</value>
      <webElementGuid>9e70281d-f4eb-4138-9ff2-962ae61c713a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/form/div/fieldset[4]/div/div/div/input</value>
      <webElementGuid>4d766d73-b481-4d6d-809c-625e44ad2e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/div/input</value>
      <webElementGuid>161dc794-006c-4ad4-9837-069b46885d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'StartDate' and @name = 'StartDate' and @placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>81c9ed2d-2726-45c8-9b7e-c82da7bf4920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
