<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Information Correct_DocumentsAreValid</name>
   <tag></tag>
   <elementGuidId>ab23bd22-cb17-4d20-aa8f-bb07ba4062e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DocumentsAreValid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DocumentsAreValid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b057be5e-c71d-4f03-b9a9-106540942bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DocumentsAreValid</value>
      <webElementGuid>f2f72469-de78-4025-809a-ebd0d848326b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>7f81d405-87ad-4f63-b3b7-b6387beb072e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentsAreValid</value>
      <webElementGuid>db1fa5d2-dc94-4839-9920-e376811cfedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>09b3614b-b6aa-4b1b-b7ab-b46f52db110b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B</value>
      <webElementGuid>398b517f-6d0f-4d45-b4b5-a2deec6f225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentsAreValid&quot;)</value>
      <webElementGuid>98887b29-4f31-4eed-9e2d-b0dd4a51a894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DocumentsAreValid']</value>
      <webElementGuid>562538db-cc7c-4d72-8d16-11a8c10ec6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section/div[2]/form/div/div[2]/div/label/input</value>
      <webElementGuid>a92dee25-07e8-4c00-9f20-becf72dfef8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>c0779903-7a5f-4f18-9aea-444f5ee81e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DocumentsAreValid' and @placeholder = 'Required' and @id = 'DocumentsAreValid' and @type = 'checkbox']</value>
      <webElementGuid>85d14d91-9869-4fe4-9606-e32325daa602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
