<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Progress_InformationCorrect</name>
   <tag></tag>
   <elementGuidId>e436069f-d2d1-4ca2-a4aa-7f9c910b2b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InformationCorrect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InformationCorrect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1bf323b-2c10-450b-a2f9-e332ffa0d013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InformationCorrect</value>
      <webElementGuid>21dc764f-9a9b-4ad0-aa26-daf7d8c1c082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>a3189155-fcaf-45c5-a3b9-220551ec9242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InformationCorrect</value>
      <webElementGuid>d8102c52-16a9-42d2-a56e-b9de3c08730b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1078cc45-5915-4dd6-9d78-1e9ac8f510c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B</value>
      <webElementGuid>a4610da1-1acb-4163-bac1-f98b0f056ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InformationCorrect&quot;)</value>
      <webElementGuid>dff4c38f-c8eb-43c7-a990-d0871b29ddce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InformationCorrect']</value>
      <webElementGuid>8681f48a-1ebd-42fa-aa12-b6144fdc366e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section/div[2]/form/div/div/div/label/input</value>
      <webElementGuid>001f0c39-5494-41f0-83ec-2e1030d58a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>39331466-7b6e-4893-976e-c65e531ec207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'InformationCorrect' and @placeholder = 'Required' and @id = 'InformationCorrect' and @type = 'checkbox']</value>
      <webElementGuid>183642e0-b7de-4e10-870a-a134e194f938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
