<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy Management_Search</name>
   <tag></tag>
   <elementGuidId>5457a0d5-9752-4b8d-8749-9b8d73c24d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69f9304c-c2ef-4cc7-82b4-e551d09d31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d218a134-21ba-4608-815e-d7461054fbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e097e92e-e3e6-4a4c-ad8d-9924c7c452b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- PAUAW</value>
      <webElementGuid>9fdeca16-83e4-4b09-88be-a69a21b3ce31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by Application ID, Device Name</value>
      <webElementGuid>688dbbf6-f77e-489b-94c9-be84c82687ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>47f4e1a7-65db-44f8-9d2b-6f14929554d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;flex my-4 md:mx-6 lg:mx-10&quot;]/div[@class=&quot;EHEmJ&quot;]/form[@class=&quot;_0k401 relative&quot;]/div[@class=&quot;jCXzE&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;Ll29B ouzj- PAUAW&quot;]</value>
      <webElementGuid>654ac608-4aa9-476f-a18c-aacb150b0c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Search']</value>
      <webElementGuid>79be58f6-90cf-436e-ae93-4a27a7150228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/section/div/div/form/div/div/input</value>
      <webElementGuid>350878ef-b763-46dd-ac95-2e41cfa509a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>383a2b70-add3-404a-8bb3-4833518abd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Search' and @placeholder = 'Search by Application ID, Device Name' and @type = 'Text']</value>
      <webElementGuid>04ee3e4d-4a60-4467-a2a8-a118716648f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
