<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Information Correct_DocumentsAreValid</name>
   <tag></tag>
   <elementGuidId>b0062231-f087-4719-bc63-1dd833807929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DocumentsAreValid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DocumentsAreValid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a833a45-3665-4b34-976d-c1d36892c6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DocumentsAreValid</value>
      <webElementGuid>44209b93-d6b2-49e2-bf58-1f216c4cc4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>8ea1ac6a-e99c-4d0b-8c7e-11356517510e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentsAreValid</value>
      <webElementGuid>333197db-6a59-424e-8953-ac5a4b5be3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a66a8573-6d17-4ff8-a59c-a35832cebafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B</value>
      <webElementGuid>0f94ee80-fab2-4eba-8774-f57f674a4ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentsAreValid&quot;)</value>
      <webElementGuid>4d1ac58f-e139-4e34-851e-32210615f7aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DocumentsAreValid']</value>
      <webElementGuid>5ac22b0f-91b6-4b62-93cd-eb3baea18d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section/div[2]/form/div/div[2]/div/label/input</value>
      <webElementGuid>7462d291-7072-4124-896a-e508f7fec656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>4eff3ff8-950e-435c-961c-890145516893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DocumentsAreValid' and @placeholder = 'Required' and @id = 'DocumentsAreValid' and @type = 'checkbox']</value>
      <webElementGuid>1d6e614e-145b-465d-86e7-e62e3cbcf27b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
