<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Progress_InformationCorrect</name>
   <tag></tag>
   <elementGuidId>a40244dd-b383-47fe-9b88-ff90c3d8bd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InformationCorrect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bafe6cd9-529b-48ce-ba53-8a71069e4273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InformationCorrect</value>
      <webElementGuid>9190bf44-c627-4969-94db-8cec9cd36d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>b8d766eb-e0ec-45af-91a8-dff48f7d21f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InformationCorrect</value>
      <webElementGuid>dc672644-43de-4d4f-bf63-eae7c3fe9fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7a39daff-9e7a-47dc-95cb-0b6bf4baf95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B</value>
      <webElementGuid>6fd9353a-7806-4f00-9ff0-ae4ce0d3269e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InformationCorrect&quot;)</value>
      <webElementGuid>4c3681dd-f67d-446b-a5a8-958c880becfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InformationCorrect']</value>
      <webElementGuid>5a6a31d0-1720-4946-90a8-dfc421f05ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div[2]/section/div[2]/form/div/div/div/label/input</value>
      <webElementGuid>2daf79b5-2631-40b9-955d-43c0fef0c084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>207c3aee-505e-4a21-8bde-ef8eb1537085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'InformationCorrect' and @placeholder = 'Required' and @id = 'InformationCorrect' and @type = 'checkbox']</value>
      <webElementGuid>e7026afb-a114-4a73-adfe-717f7707e33f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
