<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remark_RemarkContent (1)</name>
   <tag></tag>
   <elementGuidId>4d6a2073-7189-46b1-90db-2c203634cce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='RemarkContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;RemarkContent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1e51d34a-825a-47bd-94d6-ea0d7a429337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RemarkContent</value>
      <webElementGuid>6bf991ad-2bf7-4f08-a293-718e61250d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field mt-2</value>
      <webElementGuid>41828fd8-1ae8-4c2b-a7ff-2e1c24e3f449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>45ab4748-dd8e-4fca-aea1-f90cfb5a28b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/reach-portal[3]/div[2]/div[1]/div[1]/div[@class=&quot;Mow1G NW1R-&quot;]/div[2]/form[1]/div[@class=&quot;_7QyNv&quot;]/div[@class=&quot;jCXzE&quot;]/textarea[@class=&quot;Ll29B ouzj- input-field mt-2&quot;]</value>
      <webElementGuid>214ef2de-31ac-441e-8da6-ea19cdeb461b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='RemarkContent']</value>
      <webElementGuid>a39ce5f4-9b42-4b53-b2f4-37b00e7a0589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>72c37fa3-5879-46e0-9058-9363895afddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'RemarkContent']</value>
      <webElementGuid>bc9969c9-cd0d-41ce-bb99-56ded812d8d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
