<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Reason (1)</name>
   <tag></tag>
   <elementGuidId>319fc252-fb00-420e-9e50-427aedc8825f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='Reason']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Reason&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>196ee4d7-86a0-4a08-8f91-3207e9baa127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reason</value>
      <webElementGuid>8ab52532-5a09-4f11-a7e9-fada510285d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>e11dac0d-15da-450a-9513-2a7f62e98625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field</value>
      <webElementGuid>0aebd473-1f15-44aa-bf87-220152ae5613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input</value>
      <webElementGuid>9d141f67-cf64-4a9e-a263-7a1c21abca5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>cb00b673-c02b-456c-9cd0-eba3f29306d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;as0Kr&quot;]/section[@class=&quot;B-aoL js-wrapper-scrollEffect padding-footer&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;flex gap-4&quot;]/div[@class=&quot;w-5/6 flex flex-col gap-4&quot;]/form[1]/div[@class=&quot;border-shadow-container bg-white p-4&quot;]/div[@class=&quot;pb-4&quot;]/div[@class=&quot;jCXzE&quot;]/textarea[@class=&quot;Ll29B ouzj- input-field&quot;]</value>
      <webElementGuid>f64cb18a-45b9-45b3-a265-7be20b8b88cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='Reason']</value>
      <webElementGuid>2c4dfaf7-83ba-4202-9c07-5ce84332b25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div/form/div/div[5]/div/textarea</value>
      <webElementGuid>7f33e2c7-655f-4dab-9b95-d92abd935ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>edf667bb-7dad-4ba3-84fd-018637f828d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Reason' and @placeholder = 'Input']</value>
      <webElementGuid>9bf631cd-ae72-410a-ae85-e302c3d1b9df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
