<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>95722ca1-c2e0-48d0-bece-6a955f0b660f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e1bbdd4-e5dc-47a5-9a12-5ccf5cfb18bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-primary font-bold hover:underline focus:underline text-xs</value>
      <webElementGuid>800d0085-1d5b-40ee-95be-c9ec3f8991ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/ops/transaction/accounts-receivable/INV-REAR-2023-05-10-00002</value>
      <webElementGuid>054ef5ef-28c9-4b37-8056-e36e2bbb5753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>bc9334b9-61d2-46a0-927b-087fa23f1451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/section[@class=&quot;py-4 px-6 overflow-x-auto h-full&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;ttzJ8&quot;]/div[@class=&quot;Jybgt w-full h-full overflow-x-auto&quot;]/table[@class=&quot;oL4Dz&quot;]/tbody[1]/tr[@class=&quot;r7tV0&quot;]/td[@class=&quot;I4pE5 text-center&quot;]/a[@class=&quot;color-primary font-bold hover:underline focus:underline text-xs&quot;]</value>
      <webElementGuid>2d6ab245-e8fe-48ea-9c16-683bb0fc3af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[13]/a</value>
      <webElementGuid>661c51e2-7a93-4ad6-860a-c1eec765d2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View')]</value>
      <webElementGuid>581e4061-db52-400f-a08d-ce51ec56dd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.09'])[2]/following::a[1]</value>
      <webElementGuid>b7e1e799-3769-4181-8090-3d7d14d07f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.09'])[1]/following::a[1]</value>
      <webElementGuid>67675523-02f4-47d7-8c96-c2a0c726381a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INV-REAR-2023-05-10-00001'])[1]/preceding::a[1]</value>
      <webElementGuid>6c729c10-98f4-4c8d-ad5c-af861854f7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBI'])[2]/preceding::a[1]</value>
      <webElementGuid>76379d1b-dcb4-4f0b-8db7-66b30df602cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>c43ce93b-a1c9-40e4-a859-7b63ef355483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/ops/transaction/accounts-receivable/INV-REAR-2023-05-10-00002')]</value>
      <webElementGuid>8e8fa21d-869c-40e0-9337-bf79f26020d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/a</value>
      <webElementGuid>926db82e-440f-499e-90ff-ab750e421ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/ops/transaction/accounts-receivable/INV-REAR-2023-05-10-00002' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>78b824a9-3589-4917-8645-e65c28d012fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
