<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>5b2da300-1a8d-49cb-a091-a2001c2d50bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebaab2e0-0b44-422a-8e73-b410d1262417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c540fd4b-e37e-49bf-9219-c232910d61d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-primary font-bold hover:underline text-xs</value>
      <webElementGuid>f3280b75-442d-42d2-a788-ea1e3a5ef1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>274a323a-b610-47b8-8c2e-7eff8abc3bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;md:mx-6 lg:mx-10 mt-2&quot;]/div[@class=&quot;ttzJ8&quot;]/div[@class=&quot;Jybgt w-full h-full overflow-x-auto&quot;]/table[@class=&quot;oL4Dz&quot;]/tbody[1]/tr[@class=&quot;r7tV0&quot;]/td[@class=&quot;I4pE5 text-center&quot;]/div[@class=&quot;flex justify-center gap-3&quot;]/button[@class=&quot;color-primary font-bold hover:underline text-xs&quot;]</value>
      <webElementGuid>a4148682-23de-476c-9947-055823718c03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>1b5f1c4d-293a-41ff-8403-5e5e91a53148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[12]/div/button</value>
      <webElementGuid>0a71ba8e-7985-4318-9371-d909704caa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 10, 2023'])[1]/following::button[1]</value>
      <webElementGuid>c2b889af-2430-4672-8144-55d32667ca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Myself'])[1]/following::button[1]</value>
      <webElementGuid>8dff123b-e098-4fa5-a593-b345f3cddf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REDEX'])[2]/preceding::button[1]</value>
      <webElementGuid>a18a7803-691f-44e0-bec4-9fcb7ddfa291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vingroup'])[1]/preceding::button[1]</value>
      <webElementGuid>14aede1f-fe15-4f79-9f89-dd2afc8274af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>1f49e67a-dedd-4cb7-9c2c-d9cdae26a00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/div/button</value>
      <webElementGuid>56148ff5-10e4-4a6f-9b74-50019eebfba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>f65602b7-e2d5-48dc-a176-258fd82086bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
