<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_INV-REAR-2023-05-10-00002</name>
   <tag></tag>
   <elementGuidId>10e78fae-8752-493d-a26e-d7bba19e9cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/section/div/div[2]/div/div/div[2]/div[2]/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.mt-4.font-bold.CyuKG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>3bcc136b-9396-46e0-b693-8c8ec468a6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 font-bold CyuKG</value>
      <webElementGuid>b39e1029-221b-4ed7-b11f-9910201b6803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INV-REAR-2023-05-10-00002</value>
      <webElementGuid>fb956841-a36d-4646-af01-082fc6218ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/div[@class=&quot;mt-5 md:mx-6 lg:mx-10 mb-4&quot;]/div[@class=&quot;grid grid-cols-12 md:gap-5 lg:gap-8&quot;]/div[@class=&quot;col-span-9 flex flex-col gap-4&quot;]/div[@class=&quot;border-shadow-container bg-white p-4&quot;]/div[@class=&quot;grid grid-cols-2&quot;]/div[@class=&quot;mx-2&quot;]/div[@class=&quot;relative pt-0 max-w-xs&quot;]/h6[@class=&quot;mt-4 font-bold CyuKG&quot;]</value>
      <webElementGuid>349b90cd-43cf-4eeb-af86-d8a16ceac267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/div/div[2]/div/div/div[2]/div[2]/div/h6</value>
      <webElementGuid>3c8a64a1-6b06-47f5-88de-289fa27a7c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Number'])[1]/following::h6[1]</value>
      <webElementGuid>816b7832-f207-46a0-9025-7792ff1072d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Information'])[1]/following::h6[1]</value>
      <webElementGuid>96c2d6d6-e224-4da8-aeac-a18c3a4fcd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REC Item'])[1]/preceding::h6[1]</value>
      <webElementGuid>5fa21b0a-c705-4b7e-82fd-47e0ed0cadc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>f34bb9a7-6cd4-45c4-84d0-79b6432ff6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'INV-REAR-2023-05-10-00002' or . = 'INV-REAR-2023-05-10-00002')]</value>
      <webElementGuid>fc88e972-7132-48c9-96fd-0bae8671293c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
