<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>7250194c-9cf9-47e2-ae64-8a8ed6989589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'View' or . = 'View')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21bc8c4c-d946-49ae-8f7f-598cd752d8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ed2ad30-814e-47b2-97de-9f216dc50a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-primary font-bold hover:underline focus:underline text-xs</value>
      <webElementGuid>4d00c39f-d1c5-443d-b992-636fc4d6f562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>3e47dd80-e0a4-4a53-9b17-f7682bbcbdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;IUKZD&quot;]/section[@class=&quot;_4R-1K js-wrapper-scrollEffect padding-footer&quot;]/section[@class=&quot;w-full&quot;]/div[@class=&quot;md:mx-6 lg:mx-10 mt-2&quot;]/div[@class=&quot;ttzJ8&quot;]/div[@class=&quot;Jybgt w-full h-full overflow-x-auto&quot;]/table[@class=&quot;oL4Dz&quot;]/tbody[1]/tr[@class=&quot;r7tV0&quot;]/td[@class=&quot;I4pE5 text-center&quot;]/button[@class=&quot;color-primary font-bold hover:underline focus:underline text-xs&quot;]</value>
      <webElementGuid>48651144-ca71-48f1-956c-a42a416b0ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>de23c810-3845-42e5-a030-215f2d058fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/section/section/div[3]/div/div/table/tbody/tr/td[11]/button</value>
      <webElementGuid>7e52a935-bcde-4fc6-a0d7-8be2d69100f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 03, 2023'])[1]/following::button[1]</value>
      <webElementGuid>ee3df0df-1132-429b-ac81-9655daf1e964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solar'])[1]/following::button[1]</value>
      <webElementGuid>f656d5ba-3cdd-497e-9ece-93aabb0bd4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Paid: USD $1,010.00'])[1]/preceding::button[4]</value>
      <webElementGuid>b9d08297-b78b-420a-9a29-6d20fe5c515a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>6e421db4-5d4f-4d05-b1cb-d6540b77994b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/button</value>
      <webElementGuid>bbc6b86d-9c2f-4c3a-8394-163acd6446e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>c801f421-9af3-4764-833c-252ca86da502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
