<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__VintageFrom</name>
   <tag></tag>
   <elementGuidId>2eedcf14-c1bd-43ba-a11e-58864c05757a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VintageFrom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VintageFrom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9680baf7-8c8c-4847-bfad-d759ae977134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9accac16-d20a-4d3e-bd90-c175225ad275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VintageFrom</value>
      <webElementGuid>742da79c-3d40-4534-b956-cc4f82a8f016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VintageFrom</value>
      <webElementGuid>a9f7d393-20ab-4479-b7ab-1f5ffcccd495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YYYY</value>
      <webElementGuid>e2cc674b-3540-433b-a4bb-9cf6f14a9e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f8023b1b-8e77-4bdf-ba5c-84b19d8bbf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>226443a1-ebd0-4b93-ae56-faca15115d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VintageFrom&quot;)</value>
      <webElementGuid>862d855b-7a31-40af-9dd0-78a84b816fb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VintageFrom']</value>
      <webElementGuid>9f9d7dc7-44c5-4739-8b9b-cc183091fbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/form/div/div[4]/div/div/div/input</value>
      <webElementGuid>69e1eb14-a39c-4a82-9945-e11553eaa274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>324a45bd-6320-4a96-bd4e-780df69fbae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'VintageFrom' and @name = 'VintageFrom' and @placeholder = 'MM/YYYY']</value>
      <webElementGuid>509ccecb-d5f3-45d7-a90b-2c0ac9bd7b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
