<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CheckCondition</name>
   <tag></tag>
   <elementGuidId>36c7fa0a-3462-45f5-918a-fdba3ccda763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CheckCondition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CheckCondition&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e409e7ad-7d0c-4165-9445-d4e8054797f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckCondition</value>
      <webElementGuid>0284c55b-883a-4f83-8c94-76e800ce8266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>309f39ba-328e-42d8-8d18-a60c45615e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;padding-footer&quot;]/div[@class=&quot;container&quot;]/form[@class=&quot;mt-16&quot;]/div[@class=&quot;border rounded-lg px-5 py-3 mt-2 mx-auto w-1/2 bg-white border-shadow-container&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;rehash-ui-checkbox&quot;]/label[@class=&quot;rehash-ui-checkbox__container&quot;]/input[1]</value>
      <webElementGuid>2596f149-cb92-4802-8f9e-d63384934978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CheckCondition']</value>
      <webElementGuid>0d76f1b2-fdcf-44f7-89dd-aa7e9928dfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/form/div/div[6]/div/label/input</value>
      <webElementGuid>7154f724-ee1e-458c-a137-d40b093e8186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>dfaacf48-bd7e-45a4-87e2-ca6a806cc1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CheckCondition' and @type = 'checkbox']</value>
      <webElementGuid>a30a2853-4f09-4f4b-9b1c-a4a832fbff1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
