<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__VintageTo</name>
   <tag></tag>
   <elementGuidId>53660e7a-213b-4903-8cfa-382e789f247c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VintageTo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VintageTo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5df28509-58a3-4706-be89-7bd88659ed2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0465734-c1ed-48e9-a6f0-a4ade73245f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VintageTo</value>
      <webElementGuid>2b7e8e7a-599a-4bc2-a469-982a35ae430b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VintageTo</value>
      <webElementGuid>80477aff-85d3-4264-bb73-874b787e1791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YYYY</value>
      <webElementGuid>f37ac2bb-ce5a-4659-9681-9db653bb497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cfe76494-c622-40bc-a87d-eb4ac7ed95fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ll29B ouzj- input-field react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>0f509226-8fb9-4298-b9fd-be91f39d4a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VintageTo&quot;)</value>
      <webElementGuid>e3393a51-ba62-48cf-8b26-f2c44e648965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VintageTo']</value>
      <webElementGuid>ad8858a4-58ba-4507-b857-1fea6b36bc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/form/div/div[5]/div/div/div/input</value>
      <webElementGuid>4d11e176-16ef-4e8d-866b-52b1d8da0cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>47e90a66-6a27-44b4-8afb-f68a6808cdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'VintageTo' and @name = 'VintageTo' and @placeholder = 'MM/YYYY']</value>
      <webElementGuid>93b4ac41-9f93-4b49-a32e-39d32bca1a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
